version: 2

jobs:

  build:
    docker:
        - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker

      - run: 
          name: Build docker images
          command: |
            cd dockerfiles/
            ./run.sh build

      - run:
          name: Run simulator API pytest
          command: |
            cd dockerfiles/
            ./run.sh setup_run_test

  deploy:
    docker:
        - image: cimg/base:2020.01
    steps:
      - checkout
      - setup_remote_docker

      - add_ssh_keys:
          fingerprints:
            - "d4:22:e0:82:69:3b:81:31:42:e1:68:75:2e:75:4b:d5"

      - run: 
          name: Build and push docker images to Dockerhub
          command: |
            cd dockerfiles/
            ./run.sh build
            ./run.sh push

      - run:
         name: Deploy to Digital Ocean Server via Docker
         command: |
           echo "Transferring docker files to production server"
           scp -o StrictHostKeyChecking=no -r ./dockerfiles/ ${MT_USER}@${MT_SERVER}:/vagrant/

           echo "Connecting to production server..."
           ssh -o "StrictHostKeyChecking=no" ${MT_USER}@${MT_SERVER} \
           "source /root/.bash_profile && \
           cd /vagrant && \
           touch hello_test_whatuup"

        #    echo "Pulling and starting docker containers on server"
        #    cd dockerfiles/
        #    ./run.sh pull
        #    ./backup backup /db-backup/

#           TODO: Insert script call to setup and execute app/db


workflows:
  version: 2
  build-and-deploy:
    jobs:
    #   - build
      - deploy:
        #   requires:
        #     - build
          filters:
            branches:
                only: rewrite_docker_setup
            #   only: release
