version: 2
jobs:
  build:
    docker:
        - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "d4:22:e0:82:69:3b:81:31:42:e1:68:75:2e:75:4b:d5"

      - run: 
          name: Build docker images
          command: |
            echo "Building images..."
            docker build -t $DOCKER_USERNAME/minitwit-app -f ./dockerfiles/Dockerfile-minitwit .
            docker build -t $DOCKER_USERNAME/minitwit-tests -f ./dockerfiles/Dockerfile-minitwit-tests .

      - run:
          name: Run simulator api pytest on build server
          command: |
            echo "Setting up environment and running py-tests...."
            echo "yes" | docker-compose -f ./dockerfiles/docker-compose-test.yml up -d