version: '3.5'

services:
  minitwit-app:
    network_mode: host
    # image: $DOCKER_USERNAME/minitwit-app
    image: mskkitu/minitwit-app
    container_name: minitwit-app
    ports:
      - '5000:5000'
      - '5001:5001'

  minitwit-sim-tests:
    network_mode: host
    # image: $DOCKER_USERNAME/minitwit-tests
    image: mskkitu/minitwit-tests
    container_name: minitwit-tests
    depends_on: 
      - minitwit-app
