version: '3.5'

networks: 
  main:

services:
  minitwit-app:
    image: $DOCKER_USERNAME/minitwit-app
    container_name: minitwit-app
    networks: 
      - main
    depends_on:
      - minitwit-database
    ports:
      - '5000:5000'
      - '5001:5001'

  minitwit-sim-tests:
    image: $DOCKER_USERNAME/minitwit-tests
    container_name: minitwit-tests
    networks: 
      - main
    depends_on: 
      - minitwit-app

  minitwit-database:
    command: echo "Setting up postgres database..."
    image: postgres
    networks: 
      - main
    restart: always
    env_file:
      - database.env 
    ports:
      - 5432:5432
