version: '3.3'

networks:
  main:

services:
  minitwit-app:
    image: $DOCKER_USERNAME/minitwit-app
    container_name: minitwit-app
    depends_on: 
      - minitwit-database
    networks:
      - main
    ports:
      - '5000:5000'
      - '5001:5001'

  minitwit-database:
    image: postgres
    container_name: minitwit-database
    networks:
      - main
    restart: always
    env_file:
      - database.env 
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data