version: '3.3'

# volumes: 
#     db-data:
#     db-data-backup:

networks:
  main:

services:
  minitwit-app:
    image: $DOCKER_USERNAME/minitwit-app
    container_name: minitwit-app
    network_mode: host
    depends_on:
      - postgres-database
    networks:
      - main
    ports:
      - '5000:5000'
      - '5001:5001'
#    volumes:
#      - db-data:/minitwit/data/
#      - db-data-backup:/minitwit/db-data-backup/

  postgres-database:
    image: postgres
    container_name: postgres-database
    network_mode: host
    restart: always
    env_file:
      - database.env 
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    ports:
      - 5432:5432