version: '3.6'

networks:
  default:
    name: minitwit-net

services:
  minitwit-db:
    image: postgres
    container_name: minitwit-db
    restart: always
    env_file:
      - db.env 
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: